# Generated by Django 5.2.10 on 2026-03-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100, unique=True)),
                ('lane', models.CharField(choices=[('Critical', 'Critical'), ('Planned', 'Planned'), ('Preventive', 'Preventive')], max_length=20)),
                ('asset', models.CharField(max_length=200)),
                ('task', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=100)),
                ('eta', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
