# Generated by Django 5.2.10 on 2026-03-10 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_maintenanceticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='asset_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='core.asset'),
        ),
    ]
