# Generated by Django 5.2.10 on 2026-03-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_locationevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='default_office',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
    ]
