# Generated by Django 5.2.10 on 2026-03-20 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usersettings_default_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='dark_mode',
            field=models.BooleanField(default=True),
        ),
    ]
