# Generated by Django 5.2.10 on 2026-03-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Good condition', 'Good condition'), ('In Repair', 'In Repair'), ('Lost', 'Lost'), ('Critical Alert', 'Critical Alert'), ('Retired', 'Retired')], max_length=100),
        ),
    ]
